config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  authenticated :user do
    root to: 'static_pages#home', as: :authenticated_root
  end

  # Public Facing Web Pages
  root 'public#welcome'
  get '/join',    to: 'public#join_our_troop'
  get '/welcome', to: 'public#welcome'
  get '/photos',  to: 'public#photos'
  get '/eagle',   to: 'public#eagle_roll'
  get '/troop_calendar', to: 'public#troop_calendar'


  # Troop Private Pages
  resources :articles
  get 'feed' => 'articles#feed', format: 'rss'
  get '/calendar', to: 'static_pages#calendar'

  resources :scouts do
    collection do
      get 'show_inactive'
      patch 'activate'
    end
  end
  resources :requirements
  resources :scout_requirements
  resources :scout_positions
  resources :scout_trainings
  resources :scout_rank_histories
  resources :scout_merit_badges
  resources :scout_awards
  resources :scout_events
  resources :youth_awards
  resources :youth_award_requirements
  resources :positions
  resources :ranks
  resources :patrols
  resources :relationships
  resources :adults
  resources :adult_positions
  resources :adult_training_courses, only: :index
  resources :adult_trainings
  resources :adult_vehicles
  resources :adult_events
  resources :vehicles, except: :show
  resources :notifications
  resources :event_locations
  resources :events do
    collection do
      get 'calendar_export'
    end
  end
  resources :categories do
    collection do
      get 'check_category'
    end
  end

  # Reports
  get '/reports/scout_detail_report', to: 'reports#scout_detail_report'
  get '/reports/patrol_report', to: 'reports#patrol_report'
  get '/reports/event_attendance_report', to: 'reports#event_attendance_report'
  get '/reports/event_signup_sheet', to: 'reports#event_signup_sheet'
  get '/reports/ypt_report', to: 'reports#ypt_report'

  # Admin Pages
  namespace :admin do
    resources :users
    resources :file_uploads, except: [:edit, :show] do
      collection do
        get 'import_file'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  validates :text, presence: true, length: {minimum: 3, maximum: 50}

  def self.to_show
    Notification.where(active: true).where('display_until >= ?', Date.today).order(id: :asc)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_user_leader, only: [:show, :index]
  before_action :require_user_leader_full, except: [:show, :index]
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  def index
    @notifications = Notification.all
  end

  def edit
  end

  def new
    @notification = Notification.new
  end

  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html {
          flash[:success] = 'Notification was successfully updated.'
          redirect_to notifications_path
        }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html {
          flash[:success] = 'Notice was successfully created.'
          redirect_to notifications_path
        }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html {
        flash[:danger] = 'Notice was successfully destroyed.'
        redirect_to notifications_url
      }
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = Notification.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notification_params
    params.require(:notification).permit(:text,:link,:active,:display_until)
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
    <%= render 'shared/errors', obj: @notification %>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :text %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :text, class: 'form-control', placeholder: 'Title of notification', autofocus: true %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :link %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :link, class: 'form-control', placeholder: 'Link to'%>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :active %>
      </div>
      <div class="col-sm-8 ">
        <%= f.check_box :active, class: 'form-control ' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :display_until %>
      </div>
      <div class="col-sm-8 ">
        <%= f.date_select :display_until, class: 'form-control', :default =>  2.days.from_now %>
      </div>
    </div>


    <div class="form-group row">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', notifications_path, class: 'btn btn-secondary' %>
      </div>
    </div>
<% end %>

app/views/notifications/edit.html.erb
<%= content_for(:title, 'Edit Notification') %>
<div class="card col-sm-6 col-sm-offset-2">
  <div class="row">
    <div class="card-header" data-background-color="dkblue">
      <h4>Edit Notification</h4>
    </div>
    <div class="card-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<%= content_for(:title, 'Notifications') %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-icon" data-background-color="dkblue">
        <i class="fa fa-bell fa-2x" aria-hidden="true"></i>
      </div>
      <div class="card-content">
        <h4 class="card-title">Notifications
        <span class="pull-right">
          <%= link_to 'Add', new_notification_path %>
        </span></h4>
        <table class="table table-striped table-no-bordered table-hover" cellspacing="0">
          <thead>
          <tr>
            <th>Text</th>
            <th class="hidden-xs">Link</th>
            <th>Display Until</th>
            <th class="hidden-xs">Active</th>
            <th class="text-right">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @notifications.each do |notice| %>
          <tr>
            <td><%= notice.text %></td>
            <td class="hidden-xs"><%= notice.link %></td>
            <td><%= notice.display_until %></td>
            <td class="hidden-xs"><%= notice.active %></td>
            <td class="text-right">
              <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_notification_path(notice) %>
              <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, notification_path(notice), method: :delete,
                          data: {confirm: 'Are you sure you want to delete this notice?'},
                          class: 'text-danger' %>
            </td>
            <% end %>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/notifications/new.html.erb
<%= content_for(:title, 'New Notification') %>
<div class="card col-sm-6 col-sm-offset-2">
  <div class="row">
    <div class="card-header" data-background-color="dkblue">
      <h4>Add a new Notification</h4>
    </div>
    <div class="card-content">
      <%= render 'form' %>
    </div>
  </div>
</div>