config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  authenticated :user do
    root to: 'static_pages#home', as: :authenticated_root
  end

  # Public Facing Web Pages
  root 'public#welcome'
  get '/join',    to: 'public#join_our_troop'
  get '/welcome', to: 'public#welcome'
  get '/photos',  to: 'public#photos'
  get '/eagle',   to: 'public#eagle_roll'
  get '/troop_calendar', to: 'public#troop_calendar'


  # Troop Private Pages
  resources :articles
  get 'feed' => 'articles#feed', format: 'rss'
  get '/calendar', to: 'static_pages#calendar'

  resources :scouts do
    collection do
      get 'show_inactive'
      patch 'activate'
    end
  end
  resources :requirements
  resources :scout_requirements
  resources :scout_positions
  resources :scout_trainings
  resources :scout_rank_histories
  resources :scout_merit_badges
  resources :scout_awards
  resources :scout_events
  resources :youth_awards
  resources :youth_award_requirements
  resources :positions
  resources :ranks
  resources :patrols
  resources :relationships
  resources :adults
  resources :adult_positions
  resources :adult_training_courses, only: :index
  resources :adult_trainings
  resources :adult_vehicles
  resources :adult_events
  resources :vehicles, except: :show
  resources :notifications
  resources :event_locations
  resources :events do
    collection do
      get 'calendar_export'
    end
  end
  resources :categories do
    collection do
      get 'check_category'
    end
  end

  # Reports
  get '/reports/scout_detail_report', to: 'reports#scout_detail_report'
  get '/reports/patrol_report', to: 'reports#patrol_report'
  get '/reports/event_attendance_report', to: 'reports#event_attendance_report'
  get '/reports/event_signup_sheet', to: 'reports#event_signup_sheet'
  get '/reports/ypt_report', to: 'reports#ypt_report'

  # Admin Pages
  namespace :admin do
    resources :users
    resources :file_uploads, except: [:edit, :show] do
      collection do
        get 'import_file'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scout.rb
class Scout < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 250}
  validates_uniqueness_of :name

  belongs_to :patrol
  belongs_to :rank
  belongs_to :position
  has_many :scout_rank_histories
  has_many :scout_requirements
  has_many :requirements, through: :scout_requirements
  has_many :scout_merit_badges
  has_many :merit_badges, through: :scout_merit_badges
  has_many :scout_events
  has_many :events, through: :scout_events
  has_many :relationships
  has_many :users, through: :relationships
  has_many :scout_positions
  has_many :positions, through: :scout_positions
  has_many :youth_trainings
  has_many :scout_trainings, through: :youth_trainings
  has_one :address, :as => :addressable
  accepts_nested_attributes_for :address
  has_many :scout_awards
  has_many :youth_awards, through: :scout_awards
  after_create :establish_scout_rank_history


  def self.allowed_scouts(user)
    return Scout.where(active: true) if user.role?(:leader)
    return Scout.where(active: true) if user.role?(:leader_full)
    return Scout.where(active: true) if user.role?(:admin)
    Scout.where(active: true).joins(:relationships).where('relationships.user_id = ?', user)
  end

  def establish_scout_rank_history
    x = 1
    until x > rank.id
      srh = ScoutRankHistory.new(scout_id: self.id, rank_id: x, rank_completed: Date.parse('1/1/1111'))
      puts srh.inspect
      srh.save!
      x += 1
    end
  end

  def calc_rank_complete
    if self.rank_completion.blank?
      recalc_rank_complete
    end
    return self.rank_completion
  end

  def recalc_rank_complete
    self.rank_id += 1
    requirements_for_rank = Requirement.where(rank_id: self.rank_id)
    completed_requirement_count = 0
    requirements_for_rank.each do |req|
      completed_requirement = ScoutRequirement.where(requirement_id: req.id, scout_id: self.id)
      completed_requirement_count += 1 unless completed_requirement.empty?

    end
    total_requirements_needed = requirements_for_rank.count.to_f

    case self.rank_id
      when 6, 7, 8
        eagle_mb_earned = 0
        elect_mb_earned = 0
        eagle_mb_required = eagle_merit_badges_required(self.rank_id)
        elect_mb_required = elective_merit_badges_required(self.rank_id)
        total_requirements_needed += eagle_mb_required + elect_mb_required
        earned_mbs = ScoutMeritBadge.where(scout_id: self.id)
        earned_eagle_mb= {}
        earned_mb = {}
        earned_mbs.each do |smb|
          if (earned_eagle_mb.key?('Swimming') && (smb.merit_badge.name == 'Hiking' || smb.merit_badge.name == 'Cycling')) ||
              (earned_eagle_mb.key?('Hiking') && (smb.merit_badge.name == 'Swimming' || smb.merit_badge.name == 'Cycling')) ||
              (earned_eagle_mb.key?('Cycling') && (smb.merit_badge.name == 'Hiking' || smb.merit_badge.name == 'Swimming')) ||
              (earned_eagle_mb.key?('Emergency Preparedness') && smb.merit_badge.name == 'Life Saving') ||
              (earned_eagle_mb.key?('Life Saving') && smb.merit_badge.name == 'Emergency Preparedness') ||
              (earned_eagle_mb.key?('Environmental Science') && smb.merit_badge.name == 'Sustainability') ||
              (earned_eagle_mb.key?('Sustainability') && smb.merit_badge.name == 'Environmental Science')

            earned_mb[smb.merit_badge.name] = smb.completed
          else
            earned_eagle_mb[smb.merit_badge.name] = smb.completed if smb.merit_badge.eagle_required
          end
          earned_mb[smb.merit_badge.name] = smb.completed unless smb.merit_badge.eagle_required
        end

        eagle_mb_earned = earned_eagle_mb.count
        elect_mb_earned = earned_mb.count

        eagle_mb_earned = eagle_mb_required if eagle_mb_earned > eagle_mb_required
        elect_mb_earned = elect_mb_required if elect_mb_earned > elect_mb_required
        completed_requirement_count += eagle_mb_earned + elect_mb_earned
        # Do not count requirement for merit badges for progress bad
        total_requirements_needed -= 1
    end

    self.rank_id -= 1
    self.rank_completion = (completed_requirement_count / total_requirements_needed) * 100
    self.save
  end

  def elective_merit_badges_required(rank_id)
    case rank_id
      when 6
        2
      when 7
        4
      when 8
        8
      else
        0
    end
  end

  def eagle_merit_badges_required(rank_id)
    case rank_id
      when 6
        4
      when 7
        7
      when 8
        13
      else
        0
    end
  end

  def age(birthday)
    # http://stackoverflow.com/questions/819263/get-persons-age-in-ruby
    (Time.now.to_s(:number).to_i - birthday.to_time.to_s(:number).to_i)/10e9.to_i
  end

  def current_rank_date
    self.scout_rank_histories.find_by_rank_id(self.rank_id).rank_completed
  end

  def active_positions
    positions = []
    self.scout_positions.each do |scout_position|
      positions << scout_position.position.name if scout_position.current_position?
    end
    positions.join(', ')
  end

  def age_out_date(birthday)
    birthday + 18.years
  end

  def days_till_18(birthday)
    (age_out_date(birthday) - Date.today).to_i
  end

  def scout_alert
    # Set Red if less than 180 left till 18 and rank is Life
    return ['danger', 'Less than 6 months till 18th birthday'] if self.rank.name == 'Life' and days_till_18(self.birthdate).between?(0, 180)

    # Set Yellow if less than 274 left and rank is Life
    return ['warning', 'Less than 9 months till 18th birthday'] if self.rank.name == 'Life' and days_till_18(self.birthdate).between?(181, 274)

    return nil
  end

  def self.to_csv(report)
    CSV.generate(headers: true) do |csv|
      case report
        when 'scoutsReport'
          csv << %w{ID NAME GRADE AGE BIRTHDATE RANK POSITION PATROL}
          all.each do |scout|
            csv << [scout.id, scout.name, scout.grade, scout.age(scout.birthdate),
                    scout.birthdate, scout.rank.name, scout.active_positions, scout.patrol.name]
          end
        else
          csv << ["#{report} not found"]
      end
    end
  end

  require 'net/http'

  def self.import_scout(file_id)
    file ='https:' + Admin::FileUpload.find(file_id).file.url

    CSV.new(open(file), headers: true).each do |row|
      name = scout_name(row['First Name'], row['Last Name'])
      scout_record = Scout.find_or_initialize_by(name: name)
      (row['Joined Unit'].blank?) ? joined_date = '' : joined_date = Date.strptime(row['Joined Unit'], '%m/%d/%y')
      scout_record.update(name: name,
                          grade: row['Grade'],
                          birthdate: Date.strptime(row['Date of Birth'], '%m/%d/%y'),
                          rank_id: Rank.find_by_name(rank(row['Current Rank'])).id,
                          email: row['Email #1'],
                          phone: row['Home Phone'],
                          bsa_id: row['BSA ID#'],
                          joined: joined_date,
                          patrol: Patrol.find(patrol_id(row['Patrol']).id)
      )
      # Import Scout's Address
      scout_address = Address.find_or_initialize_by(addressable_id: scout_record.id, addressable_type: 'Scout')
      scout_address.update(line1: row['Home Address Line 1'],
                           line2: row['Home Address Line 2'],
                           city: row['Home City'],
                           state: row['Home State'],
                           zip: row['Home Zip']
      )
      # Import Scout's Leadership Positions
      unless row['Leadership Pos #1'].nil?
        ScoutPosition.find_or_create_by(scout_id: Scout.find_by_name(name).id,
                                        position_id: Position.find_by_name(convert_position(row['Leadership Pos #1'])).id,
                                        start_date: Date.strptime(row['Leadership Pos Date #1'], '%m/%d/%y')
        )
        unless row['Leadership Pos #2'].nil?
          ScoutPosition.find_or_create_by(scout_id: Scout.find_by_name(name).id,
                                          position_id: Position.find_by_name(convert_position(row['Leadership Pos #2'])).id,
                                          start_date: Date.strptime(row['Leadership Pos Date #2'], '%m/%d/%y')
          )
        end
      end
    end
  end

  def self.convert_position(position_name)
    case position_name
      when 'Leave No Trace Tnr'
        position_name = 'Outdoor Ethics Guide'
      when 'Asst Patrol Ldr'
        position_name = 'Asst Patrol Leader'
      when 'Asst SPL'
        position_name = 'Assistant Senior Patrol Leader'
      when 'Senior Patrol Ldr'
        position_name = 'Senior Patrol Leader'
      when 'O/A Rep'
        position_name = 'Order Of The Arrow Troop Representative'
    end
    position_name
  end

  def self.rank(rank_name)
    case rank_name
      when nil
        return 'Just Joined'
      when '1st Class'
        return 'First Class'
      when '2nd Class'
        return 'Second Class'
      else
        return rank_name
    end
  end

  def self.patrol_id(patrol_name)
    patrol = Patrol.find_by_name(patrol_name)
    if patrol.nil?
      patrol = Patrol.create(name: patrol_name)
    end
    return patrol
  end

  def self.scout_name(first, last)
    name = ''
    name += first unless first.nil?
    #name += " #{middle}" unless middle.nil?
    name += " #{last}" unless last.nil?
    #name += " #{suffix}" unless suffix.nil?
    return name
  end
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_user_leader, except: [:show]
  before_action :set_scout, only: [:show, :edit, :update, :destroy]


  # GET /scouts
  # GET /scouts.json
  def index
    @scouts = Scout.search(params[:search]).where(active: true).paginate(page: params[:page], per_page: 8)
    @scouts = Scout.search(params[:search]).paginate(page: params[:page], per_page: 8) if current_user.show_inactive_scouts

    respond_to do |format|
      format.html
      format.csv { send_data Scout.all.to_csv('scoutsReport'), filename: "scouts-#{Date.today}.csv" }
      format.json { render :index, status: :ok, location: @scout_path }
    end
  end

  def show_inactive
    @scouts = Scout.where(active: false)
  end

  # GET /scouts/1
  # GET /scouts/1.json
  def show
    @ranks = Rank.all
  end

  # GET /scouts/new
  def new
    @scout = Scout.new
    @scout.build_address
  end

  # GET /scouts/1/edit
  def edit
    @scout.build_address if @scout.address.blank?
  end

  # POST /scouts
  # POST /scouts.json
  def create
    @scout = Scout.new(scout_params)

    respond_to do |format|
      if @scout.save
        format.html {
          flash[:success] = 'Scout was successfully created.'
          redirect_to @scout
        }
        format.json { render :show, status: :created, location: @scout }
      else
        format.html { render :new }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scouts/1
  # PATCH/PUT /scouts/1.json
  def update
   if params[:active]
     @scout.active = true
     @scout.save
     redirect_to show_inactive_scouts_path and return
   end
    respond_to do |format|
      if @scout.update(scout_params)
        format.html {
          flash[:success] = 'Scout was successfully updated.'
          if @scout.active?
            redirect_to @scout
          else
            redirect_to scouts_path
          end
        }
        format.json { render :show, status: :ok, location: @scout }
      else
        format.html { render :edit }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scouts/1
  # DELETE /scouts/1.json
  def destroy
    @scout.destroy
    respond_to do |format|
      format.html {
        flash[:danger]= 'Scout was successfully deleted.'
        redirect_to scouts_url
      }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_scout
    if params[:active]
      @scout = Scout.find(params[:id])
    else
      @scout = Scout.where(active: true).find(params[:id])
    end

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def scout_params
    params.require(:scout).permit(:name, :grade, :birthdate, :patrol_id, :rank_id, :position_id, :email,
                                  :phone, :joined, :bsa_id, :active,
                                  address_attributes: [:line1, :line2, :city, :state, :zip,
                                                       :addressable_id, :addressable_type]
    )
  end

end

app/views/scouts/_age_data.erb
<div>
  <strong>Birth Date: </strong><%= scout.birthdate %>
</div>

  <strong>Days till 18: </strong><%= scout.days_till_18(scout.birthdate) %>
</div>

app/views/scouts/_compact_view.html.erb
<div class="col-sm-12">
  <div class="card">
    <div class="card-content">
      <table class="table table-responsive table-striped">
        <thead>
        <th>Scout Name</th>
        <th>Rank</th>
        <th>Patrol</th>
        <th>Position</th>
        </thead>
        <tbody>
        <% obj.each do |scout| %>
            <tr>
              <td><%= link_to scout.name, scout_path(scout) %></td>
              <td><%= scout.rank.name %></td>
              <td><%= scout.patrol.name %></td>
              <td><%= active_positions(scout) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/scouts/_form.html.erb
<%= form_for(scout, :html => {class: 'form-horizontal', id: :scout, role: 'form'}) do |f| %>
    <%= render 'shared/errors', obj: scout %>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Scout Name', autofocus: true %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-8">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :phone %>
      </div>
      <div class="col-sm-3">
        <%= f.telephone_field :phone, class: 'form-control' %>
      </div>

      <div class="control-label col-sm-2">
        <%= f.label :grade %>
      </div>
      <div class="col-sm-3">
        <%= f.number_field :grade, class: 'form-control', in: 5..12 %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :joined %>
      </div>
      <div class="col-sm-3">
        <%= f.text_field :joined, class: 'form-control datetimepicker', data: {date: scout.joined, date_format: 'YYYY-MM-DD'} %>
      </div>

      <div class="control-label col-sm-2">
        <%= f.label 'BSA ID' %>
      </div>
      <div class="col-sm-3">
        <%= f.number_field :bsa_id, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :birthdate %>
      </div>
      <div class="col-sm-3">
        <%= f.text_field :birthdate, class: 'form-control datetimepickeryear', data: {date: scout.birthdate, date_format: 'YYYY-MM-DD'} %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :rank_id %>
      </div>
      <div class="col-sm-3">
        <%= f.select :rank_id, options_for_select(Rank.all.map { |r| [r.name, r.id] }, scout.rank_id), {}, class: 'form-control' %>

      </div>

      <div class="control-label col-sm-2">
        <%= f.label :patrol_id %>
      </div>
      <div class="col-sm-3">
        <%= f.select :patrol_id, options_for_select(Patrol.all.map { |p| [p.name, p.id] }, scout.patrol_id), {}, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="togglebutton col-sm-6 col-sm-offset-4">
        <label>
          <%= f.check_box :active %>
          Active
        </label>
      </div>
    </div>

    <%= f.fields_for :address do |address| %>
        <%= render :partial => 'shared/address', :locals => {:f => address} %>
    <% end %>

    <div class="form-group row">
      <div class="col-sm-offset-4 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', :back, class: 'btn btn-secondary' %>
      </div>
    </div>
<% end %>
<script>
    $(document).ready(function () {
        $("#scout").validate({
            rules: {
                "scout[name]": {
                    required: true,
                    rangelength: [3, 250]
                },
                "scout[email]": {email: true},
                "scout[grade]": {range: [5,12]}
            },
            errorPlacement: function (error, element) {
                $(element).parent('div').parent('div').addClass('has-error');
                $(element).after(error);
            }
        });
    });
</script>

app/views/scouts/_scout.html.erb
<div id="accordion" role="tablist" aria-multiselectable="true">
  <% obj.each do |scout| %>
      <div class="card">
        <div class="card-header" role="tab" id="headingTwo<%= scout.id %>" data-background-color="dkblue">
          <h4 class="title">
              <%= link_to scout.name, scout_path(scout), class: 'hvr-push' %>
            <% unless scout.active %>
                <small>(inactive)</small>
            <% end %>
            <span class="pull-right">
              <% if current_user.role? :admin %>
                  <%= link_to "<i class='material-icons' data-toggle='tooltip' title='Delete Scout'>delete</i>".html_safe, scout,
                              method: :delete, data: {confirm: "Are you sure you wish to delete #{scout.name}?"} %>
             <% end %>
            </span>
          </h4>
        </div>
        <div id="collapseTwo<%= scout.id %>" class="collapse in" role="tabpanel" aria-labelledby="headingTwo<%= scout.id %>">
          <%= render 'scout_card_detail', obj: scout %>
        </div>
      </div>
  <% end %>
</div>

app/views/scouts/_scout_detail_nav_bar.html.erb
<div class="hidden-print">
  <ul class="nav nav-tabs" id="myTab">
    <li class="dropdown active">
      <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown">
        Ranks<b class="caret"></b>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">
        <% @ranks.each do |rank| %>
            <% unless rank.id == 1 %>
                <li>
                  <a href="#<%= rank.id %>" tabindex="-1" data-toggle="tab" onclick='$("#myTabContent").show();$("#view-scout-detail").hide()'><%= rank.name %> </a>
                </li>
            <% end %>
        <% end %>
      </ul>
    </li>

    <li><%= link_to 'Merit Badges', scout_merit_badge_path, remote: true %></li>
    <li><%= link_to 'Activities', scout_event_path, remote: true %></li>
    <li><%= link_to 'Positions Held', scout_position_path, remote: true %></li>
    <li><%= link_to 'Training', scout_training_path, remote: true %></li>
    <li><%= link_to 'Awards', scout_award_path, remote: true %></li>

  </ul>
  <div class="card">
    <div class="card-content">
      <!-- Render Scout Rank and Requirements -->
      <div id="view-scout-detail"></div>
      <div id="myTabContent" class="tab-content" style="margin-top: 0;">
        <% @ranks.each do |rank| %>
            <% unless rank.id == 1 %>
                <div class="tab-pane fade in <%= 'active' if rank.id == @scout.rank.id + 1 %>" id="<%= rank.id %>">
                  <%= render 'scouts/scout_rank_view', current_rank_selected: rank.id %>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/scouts/_scout_rank_view.html.erb
<% rank = Rank.find(current_rank_selected) %>
<% requirements = Requirement.where(rank_id: current_rank_selected).order(:sortOrder) %>
<h3 style="margin-top: 0px;"><%= rank.name %></h3>
<div>
  <table class="table table-striped table-responsive">
    <thead class="text-primary">

    <%
      rank_date, displayed_rank= nil
      completed = false
      @scout.scout_rank_histories.each do |rank_history|
        if current_rank_selected == rank_history.rank_id
          rank_date = rank_history.rank_completed
          displayed_rank = rank_history
        end
      end
      if rank_date.nil? %>

    <% else
         completed = true %>
        <tr>
          <th colspan="6">
            <div>
              <% if current_user.role? :leader_full %>
                  <% if rank_date == Date.parse('1/1/1111') %>
                      <div class="text-center">Rank Completed on Unknown Date
                        <%= link_to 'Update Date', edit_scout_rank_history_path(displayed_rank), remote: true, class: 'pull-right small' %></div>
                  <% else %>
                      <div class="text-center">Rank Completed on <%= l rank_date %>
                        <%= link_to 'Update Date', edit_scout_rank_history_path(displayed_rank), remote: true, class: 'pull-right small' %></div>
                  <% end %>
              <% end %>
            </div>
          </th>
        </tr>
    <% end %>

    <tr>
      <th><i class="fa fa-check" aria-hidden="true"></i></th>
      <th class="text-center">#</th>
      <th>Requirement</th>
      <th>Signed</th>
      <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <% requirements.each do |req| %>
        <% scout_requirement = {} %>
        <%
          if completed
            scout_requirement[:sign_off] = 'unknown'
            scout_requirement[:completed_date] = rank_date
          end
          @scout.scout_requirements.each { |test|
            if test.requirement_id == req.id
              scout_requirement[:sign_off] = test.sign_off
              scout_requirement[:completed_date] = test.completed_date
              scout_requirement[:found] = true
              scout_requirement[:id] = test.id
            end
          } %>
        <tr>
          <% unless req.req_num.nil? %>
              <td>
                <% if !scout_requirement.empty? || completed %>
                    <i class="fa fa-check" aria-hidden="true"></i>
                <% end %>
              </td>
              <td class="center">
              <span id="req_link_<%= req.id %>">
                <% if (current_user.role? :leader_full) && !req.mb %>
                    <% if scout_requirement[:found] %>
                        <%= link_to req.req_num,
                                    edit_scout_requirement_path(ScoutRequirement.find_by(scout_id: @scout.id, requirement_id: req.id)),
                                    remote: true,
                                    class: 'btn btn-sm btn-secondary' %>
                    <% else %>
                        <%= link_to req.req_num,
                                    new_scout_requirement_path(scout_id: @scout.id, req_id: req.id),
                                    remote: true,
                                    class: 'btn btn-sm btn-primary',
                                    id: "new_link_#{req.id}" %>
                    <% end %>
                    </span>
                <% else %>
                    <%= req.req_num %>
                <% end %>
                </td>
              <td><%= simple_format(req.description) %></td>
              <td id="sign_off_<%= req.id %>"><%= scout_requirement[:sign_off] %>&nbsp;</td>
              <% if scout_requirement[:completed_date] == Date.parse('1/1/1111') %>
                  <td id="completed_date_<%= req.id %>">n/a</td>
              <% else %>
                  <td id="completed_date_<%= req.id %>">
                    <%= l scout_requirement[:completed_date] unless scout_requirement[:completed_date].nil? %>
                  </td>
              <% end %>
          <% else %>
              <td colspan="6" class="text-info"><%= simple_format(req.description) %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/scouts/_show_browser.html.erb
<div class="hidden-print">

  <!--  Nav tabs between ranks -->
  <ul class="nav nav-tabs" role="tablist" >
    <% next_rank = @scout.rank_id + 1 %>
    <% Rank.all.each do |rank| %>
        <% case rank.id %>
    <% when 1 # Just Joined (hide from view)        %>
        <% when next_rank # Current rank         %>
            <li class="nav-item active">
              <a role="presentation"
                 class="nav-link"
                 data-toggle="tab"
                 aria-expanded="true"
                 href="#rank<%= rank.id %>" role="tablist"><%= rank.name %></a>
            </li>
        <% else %>
            <li class="nav-item">
              <a role="presentation" class="nav-link" data-toggle="tab" href="#rank<%= rank.id %>" role="tablist"><%= rank.name %></a>
            </li>
        <% end %>
    <% end %>
  </ul>
  <!--- tab panes -->
  <div class="tab-content">
    <% Rank.all.each do |r| %>
        <% tab_class = 'tab-pane' %>
        <% tab_class += ' active' if next_rank == r.id %>
        <div class="tab-content">
          <div role="tabpanel" class="<%= tab_class %>" id="rank<%= r.id %>" role="tabpanel">
            <%= render 'scouts/scout_rank_view', current_rank_selected: r.id %>
          </div>
        </div>
    <% end %>
  </div>
  <% if next_rank == 9 %>
      No further ranks. Eagle Palms coming soon
  <% end %>


</div>

app/views/scouts/index.html.erb
<%= content_for(:title, 'Scout Listing') %>
<div class="text-right col-sm-4 col-sm-offset-8" id="scout_view">
  <% if current_user.role? :leader %>
      <%= link_to 'Create New Scout', new_scout_path, class: 'btn btn-warning btn-round btn-xs' %>
  <% end %>
  <%= link_to 'Switch View', '#', class: 'btn btn-primary btn-xs btn-round view-toggle' %>
</div>
<div id="compact_view" style="display: none;">
  <div class="tw_pagination"><%= will_paginate %></div>
  <%= render 'scouts/compact_view', obj: @scouts %>
  <div class="tw_pagination"><%= will_paginate %></div>
</div>
<div id="expanded_view" >
  <%= render 'scout', obj: @scouts %>
  <div class="tw_pagination"><%= will_paginate %></div>
</div>
<small>Export to:
</small> <%= link_to '<i class="fa fa-file-excel-o" aria-hidden="true"></i>'.html_safe, scouts_path({:format => :csv}) %>