config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  authenticated :user do
    root to: 'static_pages#home', as: :authenticated_root
  end

  # Public Facing Web Pages
  root 'public#welcome'
  get '/join',    to: 'public#join_our_troop'
  get '/welcome', to: 'public#welcome'
  get '/photos',  to: 'public#photos'
  get '/eagle',   to: 'public#eagle_roll'
  get '/troop_calendar', to: 'public#troop_calendar'


  # Troop Private Pages
  resources :articles
  get 'feed' => 'articles#feed', format: 'rss'
  get '/calendar', to: 'static_pages#calendar'

  resources :scouts do
    collection do
      get 'show_inactive'
      patch 'activate'
    end
  end
  resources :requirements
  resources :scout_requirements
  resources :scout_positions
  resources :scout_trainings
  resources :scout_rank_histories
  resources :scout_merit_badges
  resources :scout_awards
  resources :scout_events
  resources :youth_awards
  resources :youth_award_requirements
  resources :positions
  resources :ranks
  resources :patrols
  resources :relationships
  resources :adults
  resources :adult_positions
  resources :adult_training_courses, only: :index
  resources :adult_trainings
  resources :adult_vehicles
  resources :adult_events
  resources :vehicles, except: :show
  resources :notifications
  resources :event_locations
  resources :events do
    collection do
      get 'calendar_export'
    end
  end
  resources :categories do
    collection do
      get 'check_category'
    end
  end

  # Reports
  get '/reports/scout_detail_report', to: 'reports#scout_detail_report'
  get '/reports/patrol_report', to: 'reports#patrol_report'
  get '/reports/event_attendance_report', to: 'reports#event_attendance_report'
  get '/reports/event_signup_sheet', to: 'reports#event_signup_sheet'
  get '/reports/ypt_report', to: 'reports#ypt_report'

  # Admin Pages
  namespace :admin do
    resources :users
    resources :file_uploads, except: [:edit, :show] do
      collection do
        get 'import_file'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/youth_award.rb
class YouthAward < ApplicationRecord
  validates :name, presence: true

  has_many :youth_award_requirements, dependent: :destroy
  accepts_nested_attributes_for :youth_award_requirements
  has_many :scout_awards
  has_many :scouts, through: :scout_awards
end

app/controllers/youth_awards_controller.rb
class YouthAwardsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_user_leader_full, except: :show
  before_action :set_youth_award, only: [:show, :edit, :update, :destroy]

  def new
    @youth_award = YouthAward.new
  end

  def show
  end

  def index
    @youth_awards = YouthAward.search(params[:search])
  end

  def create
    @youth_award = YouthAward.new(youth_award_params)

    respond_to do |format|
      if @youth_award.save
        format.html { redirect_to youth_awards_path, notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @youth_award }
      else
        format.html { render :new }
        format.json { render json: @youth_award.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @youth_award.update(youth_award_params)
        format.html { redirect_to youth_awards_path, notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @youth_award.destroy
    respond_to do |format|
      format.html {
        flash[:danger]= 'Award was successfully deleted.'
        redirect_to youth_awards_path
      }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_youth_award
    @youth_award = YouthAward.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def youth_award_params
    params.require(:youth_award).permit(:name, :multiple, :active, :description )
  end
end

app/views/youth_awards/_form.html.erb
<%= form_for(@youth_award, :html => {class: 'form-horizontal', id: 'youth_award', role: 'form'}) do |f| %>
    <%= render 'shared/errors', obj: @youth_award %>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name of award', autofocus: true %>
      </div>
    </div>

    <div class="form-group row">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :description, class: 'form-control', placeholder: 'Description of Award' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="togglebutton col-sm-6 col-sm-offset-4">
        <label>
          <%= f.check_box :multiple %>
          Can earn multiple times
        </label>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-offset-4 col-sm-10">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', youth_awards_path, class: 'btn btn-secondary' %>
      </div>
    </div>

<% end %>

app/views/youth_awards/edit.html.erb
<%= content_for(:title, 'Edit Existing Youth Award') %>
<div class="card col-sm-6 col-sm-offset-2">
  <div class="row">
    <div class="card-header" data-background-color="dkblue">
      <h4>Edit Reward</h4>
    </div>
    <div class="card-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/youth_awards/index.html.erb
<%= content_for(:title, 'Youth Awards') %>
<div class="col-sm-12">
  <div class="card">
    <div class="card-header" data-background-color="dkblue">
      <h4 class="card-title">Youth Award Listing
        <span class="pull-right">
        <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i>'.html_safe, new_youth_award_path %>
          </span>
      </h4>
    </div>
    <div class="card-content">
      <table class="table table-responsive table-striped">
        <thead>
        <td>Name</td>
        <td>Description</td>
        </thead>
        <tbody>
        <% @youth_awards.each do |youth_award| %>
        <tr>
          <td><%= link_to youth_award.name, youth_award_path(youth_award) %></td>
          <td><%= youth_award.description %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/youth_awards/new.html.erb
<%= content_for(:title, 'Create New Youth Award') %>
<div class="card col-sm-6 col-sm-offset-2">
  <div class="row">
    <div class="card-header" data-background-color="dkblue">
      <h4>New Award</h4>
    </div>
    <div class="card-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/youth_awards/show.html.erb
<%= content_for(:title, 'Display Youth Award') %>
<div class="card col-sm-10 col-sm-offset-1">
  <div class="row">
    <div class="card-header" data-background-color="dkblue">
      <h4><%= @youth_award.name %>
        <span class="pull-right">
        <%= link_to '<i class="fa fa-plus" data-toggle="tooltip" title="Add New Requirement" aria-hidden="true"></i> '.html_safe,
                    new_youth_award_requirement_path(youth_award_id: params[:id]) %>
          </span>
      </h4>
    </div>
    <div class="card-content">
      <div><%= @youth_award.description %></div>
      <div>
        <span class="text-primary bold">Can earn mutiple times?</span>
        <%= @youth_award.multiple %>
      </div>
      <div>
        <span class="text-primary bold">Award still available?</span>
        <%= @youth_award.active %>
      </div>
      <table class="table table-responsive table-striped">
        <thead>
        <td>#</td>
        <td>Description</td>
        <td></td>
        </thead>
        <tbody>
        <% @youth_award.youth_award_requirements.each do |requirement| %>
        <tr>
          <td><%= requirement.req_num %></td>
          <td><%= requirement.description %></td>
          <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true" data-toggle="tooltip" title="Edit Requirement"></i>'.html_safe,
                          edit_youth_award_requirement_path(requirement, youth_award_id: params[:id]) %></td>
        </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row"></div>
<div class="col-sm-12 text-center">
  <%= link_to 'Back', :back, class: 'btn btn-primary btn-sm' %>
  <%= link_to 'Edit', edit_youth_award_path(@youth_award), class: 'btn btn-sm btn-primary' if current_user.role? :leader_full %>
  <%= link_to 'Delete', @youth_award, method: :delete,
                  data: {confirm: 'Are you sure you want to delete this award?'},
                  class: 'btn btn-sm btn-danger' if current_user.role? :leader_full %>
</div>