config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  authenticated :user do
    root to: 'static_pages#home', as: :authenticated_root
  end

  # Public Facing Web Pages
  root 'public#welcome'
  get '/join',    to: 'public#join_our_troop'
  get '/welcome', to: 'public#welcome'
  get '/photos',  to: 'public#photos'
  get '/eagle',   to: 'public#eagle_roll'
  get '/troop_calendar', to: 'public#troop_calendar'


  # Troop Private Pages
  resources :articles
  get 'feed' => 'articles#feed', format: 'rss'
  get '/calendar', to: 'static_pages#calendar'

  resources :scouts do
    collection do
      get 'show_inactive'
      patch 'activate'
    end
  end
  resources :requirements
  resources :scout_requirements
  resources :scout_positions
  resources :scout_trainings
  resources :scout_rank_histories
  resources :scout_merit_badges
  resources :scout_awards
  resources :scout_events
  resources :youth_awards
  resources :youth_award_requirements
  resources :positions
  resources :ranks
  resources :patrols
  resources :relationships
  resources :adults
  resources :adult_positions
  resources :adult_training_courses, only: :index
  resources :adult_trainings
  resources :adult_vehicles
  resources :adult_events
  resources :vehicles, except: :show
  resources :notifications
  resources :event_locations
  resources :events do
    collection do
      get 'calendar_export'
    end
  end
  resources :categories do
    collection do
      get 'check_category'
    end
  end

  # Reports
  get '/reports/scout_detail_report', to: 'reports#scout_detail_report'
  get '/reports/patrol_report', to: 'reports#patrol_report'
  get '/reports/event_attendance_report', to: 'reports#event_attendance_report'
  get '/reports/event_signup_sheet', to: 'reports#event_signup_sheet'
  get '/reports/ypt_report', to: 'reports#ypt_report'

  # Admin Pages
  namespace :admin do
    resources :users
    resources :file_uploads, except: [:edit, :show] do
      collection do
        get 'import_file'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

  before_save do |category|
    category.name = category.name.downcase.titlecase
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_user_leader, except: :show
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  def check_category
    @category = Category.find_by_name(params[:category][:name])

    respond_to do |format|
      format.json { render :json => !@category }
    end
  end

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.search(params[:search])
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html {
          flash[:success] = 'Category was successfully created.'
          redirect_to categories_path
        }
        format.json { render :show, status: :created, location: @category }
        format.js
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html {
          flash[:success] = 'Category was successfully created.'
          redirect_to categories_path
        }
        format.json { render :show, status: :ok, location: @category }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html {
        flash[:danger] = 'Category was successfully destroyed.'
        redirect_to categories_url
      }
      format.json { head :no_content }
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end


end

app/views/categories/_category.html.erb
<span class="tag tag-info tag-pill"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<%= form_for(@category, remote: true, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
    <%= render 'shared/errors', obj: @category %>

    <div class="form-group row">
      <div class="control-label col-sm-2 label-floating">
        <%= f.label :name %>
      </div>
      <div class="col-sm-6 col-sm-offset-1">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Category Name', autofocus: true %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-offset-4 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
    <script>
        $(document).ready(function () {
            $("#new_category").validate({
                rules: {
                    "category[name]": {
                        required: true,
                        rangelength: [3,15],
                        remote: '/categories/check_category'
                    }
                },
                messages: {
                    "category[name]": {
                        required: 'Please specify a category name.',
                        remote: jQuery.validator.format("{0} is already in use.")
                    }
                },
                errorPlacement: function (error, element) {
                    $(element).parent('div').parent('div').addClass('has-error');
                    $(element).after(error);
                }
            });
        });
    </script>
<% end %>

app/views/categories/create.js.erb
$('#dialog').modal('toggle');
$('#dialog').on('hidden.bs.modal', function () {
    location.reload();
});

app/views/categories/edit.html.erb
<%= content_for(:title, 'Edit Category') %>
<div class="row">
  <div class="col-sm-12">
    <%= render 'form'%>
  </div>
</div>

app/views/categories/edit.js.erb
// Add the dialog title
$('#dialog h3').html("Edit Category");

// Render the edit form
$('.modal-body').html('<%= j render("categories/form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
    $('.first_input').focus()
});

app/views/categories/index.html.erb
<%= content_for(:title, 'Categories') %>
<% if (current_user.role? :leader_full)%>
    <div class="text-right">
      <%= link_to 'Create New Category', new_category_path, remote: true, class: 'btn btn-warning ' %>
    </div>
<% end %>
<div class="row">
  <% @categories.each do |category| %>
      <div class="col-sm-6">
        <div class="card card-plain">
          <div class="card-header" data-background-color="dkblue">
            <h4 class="card-title"><span id="category_name_<%= category.id %>"><%= category.name %></span>
              <% if current_user.role? :leader_full%>
              <span class="pull-right">
                <%= link_to "<i class='material-icons' data-toggle='tooltip' title='Edit Category'>create</i>".html_safe, edit_category_path(category), remote: true %>
                <%= link_to "<i class='material-icons' data-toggle='tooltip' title='Delete Category'>delete</i>".html_safe, category,
                            method: :delete, data: {confirm: "Are you sure you wish to delete #{category.name}?"} %>
                </span>
              <% end %>
            </h4>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= content_for(:title, 'Create New Category') %>
<div class="row">
  <div class="col-sm-12">
    <%= render 'form'%>
  </div>
</div>

app/views/categories/new.js.erb
// Add the dialog title
$('#dialog h3').html("Create New Category");

// Render the edit form
$('.modal-body').html('<%= j render("categories/form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
    $('.first_input').focus()
});

app/views/categories/show.html.erb
<%= content_for(:title, 'Category: ' + @category.name) %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/articles', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>

app/views/categories/update.js.erb
$('#dialog').modal('toggle');
$('#category_name_<%= @category.id%>').contents().last().replaceWith('<%= (@category.name) %>');